name: unlock_potential
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  device_info_plus: ^10.0.1
  sensors_plus: ^5.0.0
  battery_plus: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  rename: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/img/

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icon/logo.png"
  adaptive_icon_background: "assets/icon/logo_back.png"
  adaptive_icon_foreground: "assets/icon/logo_front.png" # foreground is a png defined in a zone that is 38.8% of the background
  background_color_ios: "#1c8adb"
  ios: true
  image_path_ios: "assets/icon/logo_rectangle.png"
  remove_alpha_ios: true