name: unlock_potential
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  device_info_plus: ^10.0.1
  sensors_plus: ^5.0.0
  battery_plus: ^6.0.0
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/img/
